grpc:
  server:
    address: 127.0.0.1
    port: 9900
  client:
    education-category-service:
      address: static://127.0.0.1:9900
      keep-alive-timeout: 5

spring:
  application:
    name: education-category-service
  main:
    web-application-type: NONE
  datasource:
    url: jdbc:postgresql://localhost:5432/education_category_service
    driver-class-name: org.postgresql.Driver
    username: education
    password: education
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none